### ISSUE TITLE
Any updates about releasing the codes?

### ISSUE THREAD

**Issue by freyaya123** [Tebmer/Rereading-LLM-Reasoning#1]
Hi, very interesting work, and any updates on the code of this paper?

**Comment by codelion** [comment]
I have made an independent implementation available in optillm - https://github.com/codelion/optillm/blob/main/optillm/reread.py

**Comment by Tebmer** [comment]
That's cool. Thanks for your implementation. The work is just accepted by EMNLP 2024 and we are going to release the code and experiments.
