### ISSUE TITLE
老哥，可以提交一下代码咯

### ISSUE THREAD

**Issue by davidyuan666** [Tebmer/Rereading-LLM-Reasoning#2]
太神奇了

**Comment by codelion** [comment]
我在 optillm 中提供了一个独立的实现 - https://github.com/codelion/optillm/blob/main/optillm/reread.py

**Comment by Tebmer** [comment]
That's cool. Thanks for your implementation. The work is just accepted by EMNLP 2024 and we are going to release the code and experiments.
